#%prefix% etiketi kullanılınca çıkacak mesaj
Prefix: '&8[&6waOtoMesaj&8]'
#Mesaj gidince oyuncuda çalacak ses. Kullanmak istemiyorsanız 'yok' yapın.
Ses: 'ENTITY_EXPERIENCE_ORB_PICKUP'
#Kaç saniyede bir mesaj göndersin
MesajAraligi: 300
#Mesajlar rastgele mi gönderilsin yoksa sırayla mı
Rastgele: true
#Mesajların ilk ve son satırına allttaki mesaj eklenir. Kullanmak istemiyorsanız 'yok' yapın.
BasVeSonMesaj: '&8---------------------%prefix%&8---------------------'
#Mesajlar
Mesajlar:
  1:
    - '<ortala>&aSunucumuzda &c%online% &akişi oynuyor'
    - ''
    - '<ortala>&7Bizi &6tercih &7ettiğiniz için teşekkür ederiz.'
  2:
    - '%prefix% &7Bizi tercih ettiğiniz için teşekkür ederiz'
